import type { SalesRecord } from "./data-utils"

// Sample data to use as fallback if CSV loading fails
export const sampleData: SalesRecord[] = [
  {
    Retailer: "Foot Locker",
    "Retailer ID": 1185732,
    "Invoice Date": "2021-11-12 00:00:00",
    Region: "Northeast",
    State: "Pennsylvania",
    City: "Philadelphia",
    Product: "Women's Athletic Footwear",
    "Price per Unit": 45,
    "Units Sold": 75,
    "Total Sales": 33750,
    "Operating Profit": 11812.5,
    "Operating Margin": 0.35,
    "Sales Method": "Outlet",
  },
  {
    Retailer: "Sports Direct",
    "Retailer ID": 1185733,
    "Invoice Date": "2021-10-15 00:00:00",
    Region: "West",
    State: "California",
    City: "Los Angeles",
    Product: "Men's Athletic Footwear",
    "Price per Unit": 55,
    "Units Sold": 120,
    "Total Sales": 66000,
    "Operating Profit": 23100,
    "Operating Margin": 0.35,
    "Sales Method": "Online",
  },
  {
    Retailer: "Dick's Sporting Goods",
    "Retailer ID": 1185734,
    "Invoice Date": "2021-09-22 00:00:00",
    Region: "Southeast",
    State: "Florida",
    City: "Miami",
    Product: "Men's Street Footwear",
    "Price per Unit": 65,
    "Units Sold": 90,
    "Total Sales": 58500,
    "Operating Profit": 20475,
    "Operating Margin": 0.35,
    "Sales Method": "In-store",
  },
  {
    Retailer: "JD Sports",
    "Retailer ID": 1185735,
    "Invoice Date": "2021-12-05 00:00:00",
    Region: "Midwest",
    State: "Illinois",
    City: "Chicago",
    Product: "Women's Apparel",
    "Price per Unit": 35,
    "Units Sold": 150,
    "Total Sales": 52500,
    "Operating Profit": 18375,
    "Operating Margin": 0.35,
    "Sales Method": "Online",
  },
  {
    Retailer: "Finish Line",
    "Retailer ID": 1185736,
    "Invoice Date": "2022-01-10 00:00:00",
    Region: "Southwest",
    State: "Texas",
    City: "Houston",
    Product: "Men's Apparel",
    "Price per Unit": 40,
    "Units Sold": 100,
    "Total Sales": 40000,
    "Operating Profit": 14000,
    "Operating Margin": 0.35,
    "Sales Method": "In-store",
  },
]
