import type { SalesRecord } from "./data-utils";

export const sampleData: SalesRecord[] = [
  {
    Retailer: "Foot Locker",
    "Retailer ID": 1185732,
    "Invoice Date": "2020-01-15 00:00:00",
    Region: "Northeast",
    State: "Pennsylvania",
    City: "Philadelphia",
    Product: "Women's Athletic Footwear",
    "Price per Unit": 45,
    "Units Sold": 75,
    "Total Sales": 33750,
    "Operating Profit": 11812.5,
    "Operating Margin": 0.35,
    "Sales Method": "Outlet",
  },
  {
    Retailer: "Sports Direct",
    "Retailer ID": 1185733,
    "Invoice Date": "2020-03-22 00:00:00",
    Region: "West",
    State: "California",
    City: "Los Angeles",
    Product: "Men's Athletic Footwear",
    "Price per Unit": 55,
    "Units Sold": 120,
    "Total Sales": 66000,
    "Operating Profit": 23100,
    "Operating Margin": 0.35,
    "Sales Method": "Online",
  },
  {
    Retailer: "Dick's Sporting Goods",
    "Retailer ID": 1185734,
    "Invoice Date": "2020-06-18 00:00:00",
    Region: "Southeast",
    State: "Florida",
    City: "Miami",
    Product: "Men's Street Footwear",
    "Price per Unit": 65,
    "Units Sold": 90,
    "Total Sales": 58500,
    "Operating Profit": 20475,
    "Operating Margin": 0.35,
    "Sales Method": "In-store",
  },
  {
    Retailer: "JD Sports",
    "Retailer ID": 1185735,
    "Invoice Date": "2020-09-10 00:00:00",
    Region: "Midwest",
    State: "Illinois",
    City: "Chicago",
    Product: "Women's Apparel",
    "Price per Unit": 35,
    "Units Sold": 150,
    "Total Sales": 52500,
    "Operating Profit": 18375,
    "Operating Margin": 0.35,
    "Sales Method": "Online",
  },
  {
    Retailer: "Finish Line",
    "Retailer ID": 1185736,
    "Invoice Date": "2020-11-25 00:00:00",
    Region: "Southwest",
    State: "Texas",
    City: "Houston",
    Product: "Men's Apparel",
    "Price per Unit": 40,
    "Units Sold": 100,
    "Total Sales": 40000,
    "Operating Profit": 14000,
    "Operating Margin": 0.35,
    "Sales Method": "In-store",
  },
  {
    Retailer: "Eastbay",
    "Retailer ID": 1185737,
    "Invoice Date": "2020-12-15 00:00:00",
    Region: "Northeast",
    State: "New York",
    City: "New York",
    Product: "Women's Street Footwear",
    "Price per Unit": 70,
    "Units Sold": 85,
    "Total Sales": 59500,
    "Operating Profit": 20825,
    "Operating Margin": 0.35,
    "Sales Method": "Online",
  },
  {
    Retailer: "Champs Sports",
    "Retailer ID": 1185738,
    "Invoice Date": "2021-01-08 00:00:00",
    Region: "West",
    State: "Nevada",
    City: "Las Vegas",
    Product: "Men's Athletic Footwear",
    "Price per Unit": 80,
    "Units Sold": 60,
    "Total Sales": 48000,
    "Operating Profit": 16800,
    "Operating Margin": 0.35,
    "Sales Method": "Outlet",
  },
  {
    Retailer: "Academy Sports",
    "Retailer ID": 1185739,
    "Invoice Date": "2021-02-14 00:00:00",
    Region: "Southeast",
    State: "Georgia",
    City: "Atlanta",
    Product: "Women's Apparel",
    "Price per Unit": 30,
    "Units Sold": 200,
    "Total Sales": 60000,
    "Operating Profit": 21000,
    "Operating Margin": 0.35,
    "Sales Method": "In-store",
  },
  {
    Retailer: "Big 5 Sporting Goods",
    "Retailer ID": 1185740,
    "Invoice Date": "2020-04-12 00:00:00",
    Region: "West",
    State: "California",
    City: "San Francisco",
    Product: "Women's Athletic Footwear",
    "Price per Unit": 50,
    "Units Sold": 95,
    "Total Sales": 47500,
    "Operating Profit": 16625,
    "Operating Margin": 0.35,
    "Sales Method": "In-store",
  },
  {
    Retailer: "Modell's",
    "Retailer ID": 1185741,
    "Invoice Date": "2020-08-30 00:00:00",
    Region: "Northeast",
    State: "Massachusetts",
    City: "Boston",
    Product: "Men's Street Footwear",
    "Price per Unit": 75,
    "Units Sold": 80,
    "Total Sales": 60000,
    "Operating Profit": 21000,
    "Operating Margin": 0.35,
    "Sales Method": "Outlet",
  },
];
